# docker-compose.dev.yml
version: '3.9'
services:
  api-electron:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "tsx", "src/server.ts"]
    depends_on:
      - postgres-api-bot-diario

  postgres-electron:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  evolution-lite:
    image: atendai/evolution-api-lite:v2.1.2
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  # Volumes dedicados para o ambiente de desenvolvimento
  postgres_data_dev:
  evolution_instances: