# Stage 1: build
FROM node:22-alpine AS build

WORKDIR /app

# Copia arquivos de dependência
COPY package*.json ./
RUN npm install

COPY prisma ./prisma/
COPY . .

# Garante que a variável de ambiente DATABASE_URL esteja presente durante o build
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npx prisma generate

# Stage 2: runtime
FROM node:22-alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE 3333

CMD [ "npx", "tsx", "./src/server.ts" ]